# Use an official Node runtime as the base image
FROM node:21-alpine as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --production

# Copy the rest of the application
COPY . .

# Build the NestJS app
RUN npm run build

# Stage 2 - Production image
FROM node:21-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the built files from the build stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

# Expose the port the app runs on
EXPOSE 8000
EXPOSE 8001

# Command to run the production server
CMD ["node", "dist/main.js"]
